nginx:
  image: 'docker.zicht.nl:443/nginx'
  ports:
    - "80:80"
  links:
    - php5_fpm
  volumes:
    - "${PWD}:/opt/app"

php5_fpm:
  image: 'docker.zicht.nl:443/php56-fpm'
  links:
    - mysql
    - redis
  volumes:
    - "${PWD}:/opt/app"

mysql:
  image: 'docker.zicht.nl:443/mysql'
  ports:
    - "3306:3306"

varnish:
  image: 'docker.zicht.nl:443/varnish3'
  links:
    - nginx
  ports:
    - "81:81"

redis:
  image: 'docker.zicht.nl:443/redis'
  ports:
    - "6379:6379"
