nginx:
  privileged: true
  image: 'docker.zicht.nl:443/nginx'
  ports:
    - "80:80"
  links:
    - php5_fpm
  volumes:
    - "${PWD}:/opt/app"
    - "${PWD}:${PWD}"

php5_fpm:
  privileged: true
  image: 'docker.zicht.nl:443/php56-fpm'
  links:
    - mysql
    - redis
    - solr
  volumes:
    - "${PWD}:/opt/app"
    - "${PWD}:${PWD}"

mysql:
  privileged: true
  image: 'docker.zicht.nl:443/mysql'
  ports:
    - "3306:3306"

varnish:
  privileged: true
  image: 'docker.zicht.nl:443/varnish3'
  links:
    - nginx
  ports:
    - "81:81"

redis:
  privileged: true
  image: 'docker.zicht.nl:443/redis'
  ports:
    - "6379:6379"

solr:
  privileged: true
  image: 'docker.zicht.nl:443/solr5'
  ports:
    - "8983:8983"
  volumes:
    - "${PWD}/etc/solr:/opt/solr-5.5.1/server/solr/core"