docker:
    defaults:
        compose:
            name: local

tasks:
    # We need this for more than command, so use YML "inheritance" here.
    _docker.settings: &DOCKER_SETTINGS
        opts:
            name: docker.defaults.compose.name
        set:
            _local_file: |
                cat(cwd, "/docker-compose.yml")
            _cmd: |
                cat(
                    "sudo PWD=", cwd, " COMPOSE_PROJECT_NAME=", name, " docker-compose ",
                    cat(" -f ", _local_file)
                )
    docker.up:
        <<: *DOCKER_SETTINGS
        help: |
            Put all containers for the local docker config up.
        flags:
            kill: false
            up: true
            bg: true
        args:
            container: ? ""
        pre:
            - if [ -e /var/www/localhost ]; then sudo rm /var/www/localhost; fi
            - sudo ln $(VERBOSE ? "-v") -sf $(cwd)/$(is_dir("web") ? "web/") /var/www/localhost;
        do:
            - '@(if kill) $(_cmd) kill $(container)'
            - '@(if up)   $(_cmd) up $(bg ? "-d") $(container)'

    docker.logs:
        <<: *DOCKER_SETTINGS
        help: |
            Show log output of the dockers
        do: $(_cmd) logs 

    docker.build:
        <<: *DOCKER_SETTINGS
        help: |
            Builds the containers specified in the compose file
        args:
            container: ? ""
        do: $(_cmd) build $(container)

    docker.sh:
        <<: *DOCKER_SETTINGS
        help: |
            Opens a shell to a running container
        args:
            container: ? ""
            index: "1"
        do: '@(with true as INTERACTIVE) sudo docker exec -ti $(name)_$(container)_$(index) "/bin/bash"'

    docker.ps:
        <<: *DOCKER_SETTINGS
        help: |
            Show running processes
        do: $(_cmd) ps

    docker.ips:
        <<: *DOCKER_SETTINGS
        help: |
            Dump a list of IPS per service as yml
        do: |
            echo "parameters:"
            for id in $$($(_cmd) ps -q); do
                sudo docker inspect --format '   {{ index .Config.Labels "com.docker.compose.service" }}_host: {{ .NetworkSettings.IPAddress }}' $id;
            done;

    docker.info:
        <<: *DOCKER_SETTINGS
        help: |
            Shows some useful information about the current docker setup
        do: 
            - |
                echo "Command used: $(_cmd)"
            - |
                $(z.cmd) $(z.opts) docker:ps
            - |
                echo "YAML config:"
                echo $(_local_file)
            - |
                @(if VERBOSE) 
                cat $(_local_file)
